# Generated by Django 5.1.1 on 2025-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
